# Ce fichier dit au cluster : "Voici comment aller chercher le secret db-password"
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-db-secret
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # On utilise l'identité du robot AKS
    userAssignedIdentityID: "ca732195-e4dc-4fc0-aa33-df11c7bb803b" # L'ID du robot
    keyvaultName: "kv-sre-c334bb99" # Le nom du Key Vault
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: db-password
          objectType: secret
    tenantId: "6b007274-ccb8-4f81-a19a-ff0c2659507a"